### ISSUE TITLE
Compiling with Geant4 11.2

### ISSUE THREAD

**Issue by alebertolet** [topas-nbio/TOPAS-nBio#3]
I compiled TOPAS and TOPAS-nBio with Geant4 11.2. I had to make the following changes:
 
TOPAS:
·         In TsVGeometryComponent.hh, delete class G4VTouchable; and add #include "G4VTouchable.hh"
 
TOPAS-nBio:
·         In TsEmDNAPhysics.cc and TsEmDNAPhysics_opt1.cc, change all the calls to RegisterModel to include only one argument instead of two
·         DAMARIS
o    In DrEmDNAChemistry.cc, I added #include "G4DNASancheExcitationModel.hh"
o    In DrEndRunForBiology.cc, line 42, G4PhysicsModelCatalog::Register doesn’t work anymore. There is a private method ‘InsertModel’ in the G4.11 class for G4PhysicsModelCatalog, so it is not possible to add it through this way. I just commented the line to compile.
o    In DrBiologyTimeStepAction.cc, line 130, change GetIndex for GetModelIndex (doesn’t work anyways as the model can’t be registered).

**Comment by wgshin** [comment]
Currently OpenTOPAS is compatible with Geant4 11.1
DAMARIS is not supported anymore (You can still find a damaris.tar.gz in the repository)

**Comment by wgshin** [comment]
DAMARIS is working now.
