### ISSUE TITLE
Running DNA step-by-step scorer examples

### ISSUE THREAD

**Issue by alebertolet** [topas-nbio/TOPAS-nBio#4]
I ran the examples:
 
examples/scorers/SBSDamageToDNANucleus/ExampleNucleusDNADamage.txt -> WORKED (different results than with G4 10.7.p03, I guess they changed physics or other things affecting the seed), but it looks good.
examples/scorers/ SBSDamageToDNAPlasmid/FullDNADamageInPlasmid.txt -> FAILED (segmentation fault after event 1)
examples/scorers/ SBSDamageToDNAPlasmid/SSBandDSbWithDBSCAN.txt -> FAILED (segmentation fault after event 1)

The problem is on the physics list (and that makes sense since that is one of the main things changed). Changing in these two examples
 
sv:Ph/Default/Modules = 1 "TsEmDNAPhysics”
for
sv:Ph/Default/Modules = 1 "g4em-dna”
(for example), solves the problem.

Incidentally, can you please give me write rights to the repository?
I caught an additional bug in the scorer (unrelated to G4 11): A segmentation fault is possible when no chromosome contents are provided. Adding default fChromosomeContents = {1}; in the constructor.

**Comment by jschuemann** [comment]
Thanks for checking, I changed the base permission for members, I didn't realize it was set to Read, now you should be able to write.

**Comment by JoseRamosMendez** [comment]
Thanks, Alejandro; let me check why TsEmDNAPhysics had to be changed and I’ll back to you.
Cheers,
José


From: jschuemann ***@***.***>
Date: Saturday, December 16, 2023 at 7:00 PM
To: OpenTOPAS/TOPAS-nBio ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [OpenTOPAS/TOPAS-nBio] Running DNA step-by-step scorer examples (Issue #4)

Thanks for checking, I changed the base permission for members, I didn't realize it was set to Read, now you should be able to write.

**Comment by wgshin** [comment]
It now works
